version: '3.8'

services:
  backend:
    image: node:18-alpine
    container_name: pokedex-backend
    working_dir: /app
    command: >
      sh -c "
        npm install &&
        npm start
      "
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=senha
      - DB_NAME=pokedex
      - DB_PORT=5432
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15.5
    container_name: pokedex-postgres
    environment:
      POSTGRES_DB: pokedex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
